import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runBuild } from '../src/commands/build.js';
import { runClean } from '../src/commands/clean.js';
import { runCheck } from '../src/commands/check.js';
import { loadManifest } from '../src/core/writer.js';
import { parseFrontmatter } from '../src/core/frontmatter.js';
import { cleanup, exists, read, seedProject, silence, tmpRoot, write } from './helpers.js';

let root: string;
beforeEach(async () => {
  root = await tmpRoot();
});
afterEach(async () => {
  await cleanup(root);
});

const build = (opts = {}) => silence(() => runBuild(root, { quiet: true, ...opts }));

describe('ownership', () => {
  it('refuses to overwrite a file it did not write', async () => {
    await seedProject(root, ['claude']);
    await write(root, '.claude/skills/debugging/SKILL.md', 'mine, not wondev\n');
    await expect(build()).rejects.toThrow(/not written by wondev/);
    expect(await read(root, '.claude/skills/debugging/SKILL.md')).toBe('mine, not wondev\n');
  });

  it('refuses to overwrite its own output after a hand edit', async () => {
    await seedProject(root, ['claude']);
    await build();
    const file = '.claude/skills/debugging/SKILL.md';
    await write(root, file, `${await read(root, file)}\nhand edit\n`);
    await expect(build()).rejects.toThrow(/edited since wondev wrote it/);
  });

  it('overwrites when forced', async () => {
    await seedProject(root, ['claude']);
    await build();
    const file = '.claude/skills/debugging/SKILL.md';
    await write(root, file, 'clobber me\n');
    await build({ force: true });
    expect(await read(root, file)).toContain('Reproduce first.');
  });

  it('writes nothing on a dry run', async () => {
    await seedProject(root, ['claude']);
    await build({ dryRun: true });
    expect(await exists(root, 'CLAUDE.md')).toBe(false);
    expect(await exists(root, '.wondev/.manifest.json')).toBe(false);
  });
});

describe('generated header placement', () => {
  // Cursor and Claude Code only parse frontmatter that starts at the first byte. A comment
  // above it makes the rule silently inert, which is invisible until an agent ignores it.
  it('never puts the header above frontmatter in a Cursor rule', async () => {
    await seedProject(root, ['cursor']);
    await build();
    const rule = await read(root, '.cursor/rules/skill-debugging.mdc');
    expect(rule.startsWith('---\n')).toBe(true);
    expect(rule).toContain('Generated by wondev');
  });

  it('never puts the header above frontmatter in a Claude skill', async () => {
    await seedProject(root, ['claude']);
    await build();
    const skill = await read(root, '.claude/skills/debugging/SKILL.md');
    expect(skill.startsWith('---\n')).toBe(true);
    expect(skill).toContain('name: debugging');
  });

  it('keeps the frontmatter parseable after the header is inserted', async () => {
    await seedProject(root, ['cursor']);
    await build();
    const rule = await read(root, '.cursor/rules/memory-architecture.mdc');
    const { data } = parseFrontmatter(rule, 'rule.mdc');
    expect(data['alwaysApply']).toBe(true);
    expect(data['description']).toBeTruthy();
  });

  it('puts the header first when there is no frontmatter', async () => {
    await seedProject(root, ['windsurf']);
    await build();
    const rule = await read(root, '.windsurf/rules/skill-debugging.md');
    expect(rule.startsWith('<!-- Generated by wondev')).toBe(true);
  });
});

describe('managed regions', () => {
  it('appends to an existing file without --force and keeps its content', async () => {
    await seedProject(root, ['agents']);
    await write(root, 'AGENTS.md', '# Mine\n\nPrecious paragraph.\n');
    await build();
    const content = await read(root, 'AGENTS.md');
    expect(content).toContain('Precious paragraph.');
    expect(content).toContain('<!-- wondev:start -->');
  });

  it('ignores edits made outside the markers', async () => {
    await seedProject(root, ['agents']);
    await build();
    const original = await read(root, 'AGENTS.md');
    await write(root, 'AGENTS.md', `A note above.\n\n${original}`);
    // No conflict: the managed span is untouched, so this must not need --force.
    await expect(build()).resolves.toBeUndefined();
    expect(await read(root, 'AGENTS.md')).toContain('A note above.');
  });

  it('detects an edit made inside the markers', async () => {
    await seedProject(root, ['agents']);
    await build();
    const content = await read(root, 'AGENTS.md');
    const tampered = content.replace('The system is a single binary.', 'Tampered.');
    expect(tampered).not.toBe(content);
    await write(root, 'AGENTS.md', tampered);
    await expect(build()).rejects.toThrow(/edited since wondev wrote it/);
  });

  it('replaces the region in place rather than appending a second one', async () => {
    await seedProject(root, ['agents']);
    await build();
    await write(
      root,
      '.wondev/memory/architecture.md',
      '---\ntitle: Architecture\nalways: true\n---\n\nTwo binaries now.\n',
    );
    await build();
    const content = await read(root, 'AGENTS.md');
    expect(content.match(/wondev:start/g)).toHaveLength(1);
    expect(content).toContain('Two binaries now.');
    expect(content).not.toContain('One binary.');
  });
});

describe('stale output', () => {
  it('removes generated files when their source is deleted', async () => {
    await seedProject(root, ['claude']);
    await build();
    expect(await exists(root, '.claude/commands/review.md')).toBe(true);

    const fs = await import('node:fs/promises');
    await fs.rm(`${root}/.wondev/commands/review.md`);
    await build();

    expect(await exists(root, '.claude/commands/review.md')).toBe(false);
    const manifest = await loadManifest(root);
    expect(manifest.files['.claude/commands/review.md']).toBeUndefined();
  });
});

describe('clean', () => {
  it('deletes files it owns entirely and prunes their directories', async () => {
    await seedProject(root, ['claude']);
    await build();
    await silence(() => runClean(root));
    expect(await exists(root, '.claude/skills/debugging/SKILL.md')).toBe(false);
    expect(await exists(root, '.claude')).toBe(false);
    expect(await exists(root, '.wondev/.manifest.json')).toBe(false);
  });

  it('strips only the region from a file it shares, leaving the rest byte for byte', async () => {
    await seedProject(root, ['agents']);
    const original = '# Mine\n\nPrecious paragraph.\n';
    await write(root, 'AGENTS.md', original);
    await build();
    await silence(() => runClean(root));
    expect(await read(root, 'AGENTS.md')).toBe(original);
  });

  it('leaves the source tree untouched', async () => {
    await seedProject(root, ['claude']);
    await build();
    await silence(() => runClean(root));
    expect(await exists(root, '.wondev/skills/debugging/SKILL.md')).toBe(true);
  });
});

describe('check', () => {
  it('passes immediately after a build', async () => {
    await seedProject(root, ['claude', 'agents', 'cursor']);
    await build();
    await expect(silence(() => runCheck(root))).resolves.toBeUndefined();
  });

  it('fails when a generated file is missing', async () => {
    await seedProject(root, ['claude']);
    await build();
    const fs = await import('node:fs/promises');
    await fs.rm(`${root}/CLAUDE.md`);
    await expect(silence(() => runCheck(root))).rejects.toThrow(/do not match/);
  });

  it('fails when the source changed but no rebuild happened', async () => {
    await seedProject(root, ['claude']);
    await build();
    await write(
      root,
      '.wondev/memory/architecture.md',
      '---\ntitle: Architecture\nalways: true\n---\n\nChanged.\n',
    );
    await expect(silence(() => runCheck(root))).rejects.toThrow(/do not match/);
  });

  it('fails on a source error before it looks at output', async () => {
    await seedProject(root, ['claude']);
    await write(root, '.wondev/skills/broken/SKILL.md', '---\nname: broken\n---\n\nno description\n');
    await expect(silence(() => runCheck(root))).rejects.toThrow(/error/);
  });
});

describe('manifest', () => {
  it('stores forward-slash paths so Windows and Linux agree', async () => {
    await seedProject(root, ['claude']);
    await build();
    const manifest = await loadManifest(root);
    for (const key of Object.keys(manifest.files)) {
      expect(key).not.toContain('\\');
    }
  });

  it('treats a corrupt manifest as empty rather than crashing', async () => {
    await seedProject(root, ['claude']);
    await build();
    await write(root, '.wondev/.manifest.json', '{ not json');
    const manifest = await loadManifest(root);
    expect(manifest.files).toEqual({});
    // Existing output now looks untracked, which must surface as a refusal, not a clobber.
    await expect(build()).rejects.toThrow(/not written by wondev/);
  });

  it('is stable across repeated builds', async () => {
    await seedProject(root, ['claude', 'agents']);
    await build();
    const first = await read(root, '.wondev/.manifest.json');
    await build();
    expect(await read(root, '.wondev/.manifest.json')).toBe(first);
  });
});
