import path from 'node:path';
import type { RenderedFile, WriteMode } from './model.js';
import { WONDEV_DIR } from './config.js';
import { WondevError } from '../util/errors.js';
import {
  normalizeEol,
  pruneEmptyDirs,
  readFileIfExists,
  removeFile,
  sha256,
  writeFileAtomic,
} from '../util/fs.js';
import { absFrom } from '../util/paths.js';
import { wondevVersion } from '../util/version.js';
import { MANIFEST_SCHEMA_VERSION } from './schema.js';

export const MANIFEST_REL = `${WONDEV_DIR}/.manifest.json`;
export const REGION_START = '<!-- wondev:start -->';
export const REGION_END = '<!-- wondev:end -->';
export const GENERATED_HEADER =
  '<!-- Generated by wondev. Edit .wondev/ and run `wondev build`. -->';

export interface ManifestEntry {
  /** sha256 of the span wondev owns: the whole file, or the text between the markers. */
  hash: string;
  target: string;
  mode: WriteMode;
}

export interface Manifest {
  version: number;
  /** The wondev release that produced these files. Absent in manifests written before 0.2. */
  wondevVersion?: string;
  files: Record<string, ManifestEntry>;
}

export function emptyManifest(): Manifest {
  return { version: MANIFEST_SCHEMA_VERSION, files: {} };
}

export async function loadManifest(root: string): Promise<Manifest> {
  const raw = await readFileIfExists(absFrom(root, MANIFEST_REL));
  if (raw === null) return emptyManifest();

  let parsed: Manifest;
  try {
    parsed = JSON.parse(raw) as Manifest;
  } catch {
    // A corrupt manifest must not brick the project; treating it as empty makes every
    // existing output look untracked, which surfaces as a refuse-to-clobber message.
    return emptyManifest();
  }

  if (typeof parsed !== 'object' || parsed === null || typeof parsed.files !== 'object') {
    return emptyManifest();
  }

  // A manifest from the future is refused rather than reinterpreted: guessing at an unknown
  // format risks deleting files this build cannot correctly account for.
  if (typeof parsed.version === 'number' && parsed.version > MANIFEST_SCHEMA_VERSION) {
    throw new WondevError(
      `${MANIFEST_REL} uses format version ${parsed.version}, but this wondev supports up to ${MANIFEST_SCHEMA_VERSION}.`,
      'Upgrade wondev: npm install -g wondev@latest',
    );
  }

  const manifest: Manifest = {
    version: parsed.version ?? MANIFEST_SCHEMA_VERSION,
    files: parsed.files ?? {},
  };
  if (typeof parsed.wondevVersion === 'string') manifest.wondevVersion = parsed.wondevVersion;
  return manifest;
}

export async function saveManifest(root: string, manifest: Manifest): Promise<void> {
  const sorted: Manifest = {
    version: MANIFEST_SCHEMA_VERSION,
    wondevVersion: wondevVersion(),
    files: Object.fromEntries(
      Object.entries(manifest.files).sort(([a], [b]) => a.localeCompare(b)),
    ),
  };
  await writeFileAtomic(absFrom(root, MANIFEST_REL), `${JSON.stringify(sorted, null, 2)}\n`);
}

export type PlanAction = 'create' | 'update' | 'unchanged' | 'adopt';
export type ConflictReason = 'untracked' | 'modified';

export interface PlanItem {
  path: string;
  mode: WriteMode;
  target: string;
  action: PlanAction;
  /** Exact bytes to write. Already includes header and markers. */
  nextContent: string;
  /** Hash of the span wondev owns, stored in the manifest after a successful write. */
  ownedHash: string;
  conflict?: ConflictReason;
}

function regionInner(content: string): string {
  return `\n${GENERATED_HEADER}\n\n${content.trim()}\n`;
}

function buildRegionBlock(content: string): string {
  return `${REGION_START}${regionInner(content)}${REGION_END}`;
}

const REGION_RE = new RegExp(`${REGION_START}([\\s\\S]*?)${REGION_END}`);

/** The text wondev owns inside an existing file, or null when it owns nothing yet. */
export function extractRegion(fileContent: string): string | null {
  const m = REGION_RE.exec(fileContent);
  return m ? (m[1] ?? '') : null;
}

function replaceRegion(existing: string, content: string): string {
  const block = buildRegionBlock(content);
  if (REGION_RE.test(existing)) {
    return existing.replace(REGION_RE, () => block);
  }
  // Additive: the user's file is preserved and the managed block is appended. This is why
  // `region` is the default mode -- adopting an existing AGENTS.md never destroys anything.
  const base = existing.trimEnd();
  return base === '' ? `${block}\n` : `${base}\n\n${block}\n`;
}

const LEADING_FRONTMATTER = /^---[ \t]*\r?\n[\s\S]*?\r?\n---[ \t]*\r?\n/;

/**
 * Prepend the "generated" notice, but never above a frontmatter block.
 *
 * Cursor only recognises a `.mdc` rule when its YAML frontmatter starts at the first byte;
 * a comment above it makes the rule silently inert. The same is true of Claude Code skills.
 */
function wholeContent(content: string): string {
  const trimmed = content.trim();
  const fm = LEADING_FRONTMATTER.exec(trimmed);
  if (fm && fm[0]) {
    const body = trimmed.slice(fm[0].length).trim();
    return `${fm[0]}\n${GENERATED_HEADER}\n\n${body}\n`;
  }
  return `${GENERATED_HEADER}\n\n${trimmed}\n`;
}

/**
 * Decide what would happen to each rendered file without touching disk.
 *
 * The refusal rules live here so `build`, `--dry-run`, and `check` all agree on what counts
 * as a conflict.
 */
export async function planWrites(
  root: string,
  files: RenderedFile[],
  targetOf: Map<string, string>,
  manifest: Manifest,
): Promise<PlanItem[]> {
  const plan: PlanItem[] = [];

  for (const file of files) {
    const abs = absFrom(root, file.path);
    const existingRaw = await readFileIfExists(abs);
    const existing = existingRaw === null ? null : normalizeEol(existingRaw);
    const entry = manifest.files[file.path];
    const target = targetOf.get(file.path) ?? 'unknown';

    if (file.mode === 'whole') {
      const next = wholeContent(file.content);
      const ownedHash = sha256(next);

      if (existing === null) {
        plan.push({ path: file.path, mode: 'whole', target, action: 'create', nextContent: next, ownedHash });
        continue;
      }
      if (!entry) {
        plan.push({
          path: file.path, mode: 'whole', target, action: 'update',
          nextContent: next, ownedHash, conflict: 'untracked',
        });
        continue;
      }
      if (sha256(existing) !== entry.hash) {
        plan.push({
          path: file.path, mode: 'whole', target, action: 'update',
          nextContent: next, ownedHash, conflict: 'modified',
        });
        continue;
      }
      plan.push({
        path: file.path, mode: 'whole', target,
        action: existing === next ? 'unchanged' : 'update',
        nextContent: next, ownedHash,
      });
      continue;
    }

    // region mode
    const inner = regionInner(file.content);
    const ownedHash = sha256(inner);

    if (existing === null) {
      plan.push({
        path: file.path, mode: 'region', target, action: 'create',
        nextContent: `${buildRegionBlock(file.content)}\n`, ownedHash,
      });
      continue;
    }

    const currentInner = extractRegion(existing);
    const next = replaceRegion(existing, file.content);

    if (currentInner === null) {
      // No markers yet. Appending is non-destructive, so this is allowed without --force.
      plan.push({ path: file.path, mode: 'region', target, action: 'adopt', nextContent: next, ownedHash });
      continue;
    }
    if (!entry) {
      plan.push({
        path: file.path, mode: 'region', target, action: 'update',
        nextContent: next, ownedHash, conflict: 'untracked',
      });
      continue;
    }
    if (sha256(currentInner) !== entry.hash) {
      plan.push({
        path: file.path, mode: 'region', target, action: 'update',
        nextContent: next, ownedHash, conflict: 'modified',
      });
      continue;
    }
    plan.push({
      path: file.path, mode: 'region', target,
      action: currentInner === inner ? 'unchanged' : 'update',
      nextContent: next, ownedHash,
    });
  }

  return plan;
}

export function conflictsIn(plan: PlanItem[]): PlanItem[] {
  return plan.filter((p) => p.conflict !== undefined);
}

export function describeConflicts(conflicts: PlanItem[]): WondevError {
  const lines = conflicts.map((c) =>
    c.conflict === 'untracked'
      ? `  ${c.path} — exists but was not written by wondev`
      : `  ${c.path} — has been edited since wondev wrote it`,
  );
  return new WondevError(
    `Refusing to overwrite ${conflicts.length} file(s):\n${lines.join('\n')}`,
    'Re-run with --force to overwrite, or move your edits into .wondev/ first.',
  );
}

export interface ApplyResult {
  written: PlanItem[];
  removed: RemovedFile[];
}

/**
 * Write the plan and reconcile the manifest.
 *
 * Files the manifest still lists but the current render no longer produces are removed, so
 * deleting a skill from `.wondev/` cleans up its generated output everywhere.
 */
export async function applyPlan(
  root: string,
  plan: PlanItem[],
  manifest: Manifest,
): Promise<ApplyResult> {
  const written: PlanItem[] = [];

  for (const item of plan) {
    if (item.action !== 'unchanged') {
      await writeFileAtomic(absFrom(root, item.path), item.nextContent);
      written.push(item);
    }
    manifest.files[item.path] = { hash: item.ownedHash, target: item.target, mode: item.mode };
  }

  const rendered = new Set(plan.map((p) => p.path));
  const stale = Object.keys(manifest.files).filter((p) => !rendered.has(p));
  const removed: RemovedFile[] = [];
  for (const p of stale) {
    const entry = manifest.files[p];
    if (!entry) continue;
    const outcome = await removeOwned(root, p, entry.mode);
    if (outcome !== 'missing') removed.push({ path: p, outcome });
    delete manifest.files[p];
  }

  await saveManifest(root, manifest);
  return { written, removed };
}

/** What happened to a file wondev stopped owning. */
export type RemoveOutcome = 'deleted' | 'stripped' | 'missing';

export interface RemovedFile {
  path: string;
  outcome: RemoveOutcome;
}

/**
 * Remove wondev's contribution to a file. A `whole` file is deleted outright; a `region`
 * file loses only its managed block and keeps whatever the user wrote around it, which is
 * why the two outcomes are reported separately rather than both as "removed".
 */
export async function removeOwned(
  root: string,
  rel: string,
  mode: WriteMode,
): Promise<RemoveOutcome> {
  const abs = absFrom(root, rel);
  const raw = await readFileIfExists(abs);
  if (raw === null) return 'missing';

  if (mode === 'whole') {
    await removeFile(abs);
    await pruneEmptyDirs(path.dirname(abs), root);
    return 'deleted';
  }

  const content = normalizeEol(raw);
  if (!REGION_RE.test(content)) return 'missing';
  const stripped = content.replace(REGION_RE, '').replace(/\n{3,}/g, '\n\n').trim();
  if (stripped === '') {
    await removeFile(abs);
    await pruneEmptyDirs(path.dirname(abs), root);
    return 'deleted';
  }
  await writeFileAtomic(abs, `${stripped}\n`);
  return 'stripped';
}

/** Remove everything the manifest lists, then drop the manifest itself. */
export async function cleanAll(root: string, manifest: Manifest): Promise<RemovedFile[]> {
  const removed: RemovedFile[] = [];
  for (const [rel, entry] of Object.entries(manifest.files)) {
    const outcome = await removeOwned(root, rel, entry.mode);
    if (outcome !== 'missing') removed.push({ path: rel, outcome });
  }
  await removeFile(absFrom(root, MANIFEST_REL));
  return removed.sort((a, b) => a.path.localeCompare(b.path));
}
